name: 08-variables-secretos

on:
  workflow_dispatch:

env:
  MENSAJE: "Hola desde variable global"

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar variable global
        run: echo $MENSAJE

      - name: Variable local
        env:
          MENSAJE_LOCAL: "Hola desde variable local"
        run: echo $MENSAJE_LOCAL

      - name: Mostrar secreto
        run: echo "Los secretos se usan con \${{ secrets.NOMBRE_SECRETO }}"