name: 18-inyecciondependencias

on:
  workflow_dispatch:

jobs:
  instalar-dependencias:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: echo "Dependencias instaladas correctamente"